GameTag.create(game_title: 'Monster Hunter: World')
GameTag.create(game_title: 'リングフィット アドベンチャー')
GameTag.create(game_title: 'Minecraft')
GameTag.create(game_title: 'Fortnite')
GameTag.create(game_title: 'ドラゴンクエストXI')
GameTag.create(game_title: 'Grand Theft Auto V')
GameTag.create(game_title: 'FINAL FANTASY VII')
GameTag.create(game_title: 'SEKIRO')
GameTag.create(game_title: 'PERSONA5')
GameTag.create(game_title: 'NieR:Automata')
GameTag.create(game_title: 'Apex Legends')
GameTag.create(game_title: 'Dead by Daylight')
GameTag.create(game_title: "Tom Clancy's Rainbow Six: Siege")
GameTag.create(game_title: 'Ghost of Tsushima')
GameTag.create(game_title: 'パワフルプロ野球2020')
GameTag.create(game_title: 'DEATH STRANDING')
GameTag.create(game_title: 'League of Legends')
GameTag.create(game_title: 'VALORANT')
GameTag.create(game_title: 'Call of Duty:Modern Warfare')
GameTag.create(game_title: 'World of Tanks')
GameTag.create(game_title: 'Dota 2')
GameTag.create(game_title: 'Counter-Strike')
GameTag.create(game_title: 'Fall Guys: Ultimate Knockout')
GameTag.create(game_title: "PlayerUnknown's Battlegrounds")
GameTag.create(game_title: 'Garena Free Fire')
GameTag.create(game_title: 'Medieval Dynasty')
GameTag.create(game_title: 'Escape From Tarkov')
GameTag.create(game_title: 'Spelunky 2')
GameTag.create(game_title: 'Dragon Ball FighterZ')
GameTag.create(game_title: 'Super Mario 3D All-Stars')
GameTag.create(game_title: 'NBA 2K21')
GameTag.create(game_title: 'Rocket League')
GameTag.create(game_title: 'Phoenix Wright: Ace Attorney Trilogy HD')
GameTag.create(game_title: 'Overwatch')
GameTag.create(game_title: 'Black Desert Online')
GameTag.create(game_title: 'World of Warcraft')
GameTag.create(game_title: 'Hearthstone')
GameTag.create(game_title: 'Teamfight Tactics')
GameTag.create(game_title: 'Among Us')
GameTag.create(game_title: 'あつまれ どうぶつの森')
GameTag.create(game_title: 'マリオカート8 デラックス')
GameTag.create(game_title: 'Pokémon Sword and Shield')
GameTag.create(game_title: 'Splatoon 2')
GameTag.create(game_title: '世界のアソビ大全51')
GameTag.create(game_title: 'ゼルダの伝説 Breath of the Wild')
GameTag.create(game_title: 'Xenoblade')
GameTag.create(game_title: 'GRAND SUMMONERS')
GameTag.create(game_title: 'Lords Mobile')
GameTag.create(game_title: 'CRYSTAL OF RE:UNION')
GameTag.create(game_title: 'SINoALICE -シノアリス-')
GameTag.create(game_title: 'Shadowverse')
GameTag.create(game_title: 'THE IDOLM@STER SHINY COLORS')
GameTag.create(game_title: 'アズールレーン')
GameTag.create(game_title: 'アークナイツ')
GameTag.create(game_title: 'DRAGON QUEST RIVALS')
GameTag.create(game_title: 'プリンセスコネクト！Re:Dive')
GameTag.create(game_title: 'GRANBLUE FANTASY')
GameTag.create(game_title: 'パズル&ドラゴンズ')
GameTag.create(game_title: 'モンスターストライク')
GameTag.create(game_title: 'クイズRPG 魔法使いと黒猫のウィズ')
GameTag.create(game_title: '白猫プロジェクト')
GameTag.create(game_title: 'LINE：ディズニー ツムツム')
GameTag.create(game_title: 'Clash of Clans')
GameTag.create(game_title: 'Pokémon GO')
GameTag.create(game_title: 'Candy Crush Saga')
GameTag.create(game_title: '神撃のバハムート')
GameTag.create(game_title: 'Fate/Grand Order')
